### ISSUE TITLE
Can't connect to NZBHydra from Radarr/Sonarr etc

### ISSUE THREAD

**Issue by robflate** [duhio/docker-compose-usenet#11]
I've tried to add NZBHydra as an indexer in Radarr but I get this in my Radarr logs;

```
HTTP Error - Res: [GET] https://nzbhydra.mydomain.com/api?t=caps&apikey=(removed) 401.Unauthorized
401 Unauthorized
```
If I visit the URL (with my API key) in a browser I get what looks like valid XML but Radarr just fails and throws the error. I'm using the following info in Radarr;

```
Custom newznab
Name: NZBHydra
Enable RSS Sync: yes
Enable Search: yes
URL: https://nzbhydra.mydomain.com/
API Key: my-api-key-from-nzbhydra
```
Wondering how others are getting this to work. Thanks.

**Comment by stevewm** [comment]
You're seeing this as you're accessing the external password protected endpoint and providing no password. 

Instead, use the container name and port. For adding hydra as an indexer it'll just be `http://nzbhydra:5076`. Similar applies for other services accessing one another, such as Sabnzbd in Radarr.

**Comment by robflate** [comment]
Thanks. That was it. Appreciate the help.
