### ISSUE TITLE
Plex remote access outside network

### ISSUE THREAD

**Issue by robflate** [duhio/docker-compose-usenet#15]
Does this setup allow remote Plex access from outside the host network (for example, say I'm using the Plex iOS app from a friends house)? In my list of servers in Plex it shows as `Indirect`, with an exclamation point rather than remote. Also, the `Remote Access` section of Plex server says `Not available outside your network`. Do I need to forward port 32400 on my router to the IP of the machine running docker?

**Comment by stevewm** [comment]
> Do I need to forward port 32400 on my router to the IP of the machine running docker?

You will, along with manually specifying the public port (32400).
