### ISSUE TITLE
Ombi 401 errors through reverse proxy

### ISSUE THREAD

**Issue by robflate** [duhio/docker-compose-usenet#19]
I can access Ombi through the reverse proxy (traefik) but the settings pages are blank and search does not work. It works when connecting through localhost on the machine where docker is running. The browser console shows lots of 401 errors. Could it be something to do with headers not getting sent along? Sorry, my knowledge of this stuff is limited.

![ombi 2018-05-02 13-56-06](https://user-images.githubusercontent.com/4172375/39524455-f74e6070-4e10-11e8-84a7-551a61026e34.png)

**Comment by stevewm** [comment]
Looks like this is an incompatibility between the latest version of Ombi and the use of basic auth as per this issue: https://github.com/tidusjar/Ombi/issues/1984

Not sure what the best fix for this is at the moment.

**Comment by addbee** [comment]
I've made a quick attempt at this with a PR https://github.com/duhio/docker-compose-usenet/pull/20

I've implemented these changes on my own install and have been able to access ombi since.

I can also get to plex.example.com without an SSH tunnel

**Comment by robflate** [comment]
Thanks. I added a comment to the PR.

**Comment by stevewm** [comment]
Resolved by @adam-bell's PR. Closing this at last!
