### ISSUE TITLE
forward_auth branch duhio/twain

### ISSUE THREAD

**Issue by addbee** [duhio/docker-compose-usenet#22]
Hi there

Is the docker image duhio/twain progressed enough to be made public? 

The forward auth option looks interesting so i'd like to play around with options for automatically configuring twain, if you have a docker image that can be made public

**Comment by stevewm** [comment]
At present, it's not in a state to share. That branch is mostly for experimentation around the idea of forward auth in the stack. 

twain itself is probably not fit for purpose in its current state - I don't think I'd be comfortable having it secure services given its immaturity (lack of tests, etc).
