### ISSUE TITLE
Heimdall Save issue when going through Traefik

### ISSUE THREAD

**Issue by robflate** [duhio/docker-compose-usenet#25]
Is anyone who uses this setup having problems with Heimdall? It used to work fine but now I am unable to save changes in Heimdall. If I change a setting or add a new Application, clicking save does not save the changes.

A quick test is to open Heimdall, go to `Settings`, click `Edit` next to `Homepage Search`, change the toggle and click `Save`. For me, the change is not saved.

I've asked on the Heimdall github but I'm thinking it might be a problem related to Traefik.

Anyway, I'd love to know if this works for anyone else using the latest releases of Docker, Traefik and Heimdall. Thanks.

**Comment by stevewm** [comment]
Looks like something changed that has broken this (it was working before), as per [the issue you commented on](https://github.com/linuxserver/Heimdall/issues/245). Will investigate this to see what's going on.
