### ISSUE TITLE
nzbget authentication not working

### ISSUE THREAD

**Issue by lpmartineau** [duhio/docker-compose-usenet#28]
Thank you for providing this docker-compose file. Saved me a lot of work and effort.

I removed the sabnzbd section from the docker-compose.yaml file and put in the nzbget section that you provide in the readme. I was able to run docker-compose up -d and I can login to any of the services except nzbget. It is not accepting the username and password that I placed in the .env file. The same user and pass is working fine for all of the other services.

This is what I added to the docker-compose.yaml file:

> nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DOWNLOAD}/watch:/watch
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "6789"
      traefik.frontend.rule: "Host:nzbget.${DOMAIN}"
      traefik.frontend.auth.basic: "${HTPASSWD}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

Any ideas?

Thank you

**Comment by racurry** [comment]
@lpmartineau NZBGet comes with default credentials baked into it on a fresh install.

https://wiki.archlinux.org/index.php/NZBGet#Default_NZBGet_credentials
