### ISSUE TITLE
Having issues with permissions/env file not passing GUID and PUID correctly

### ISSUE THREAD

**Issue by FrankExcViews** [duhio/docker-compose-usenet#4]
I believe I am having a few issues with GUID/PUID in my environment file. I have the following at the end of my .env file:

PGID=1000
PUID=1000

These match the user I am running Docker from as well as the user who is set as the owner of the folders on my server.

However, I get an error message when trying to import my existing tvshows/movies into Sonarr and Radarr about user abc not having permissions to these volumes.

I also get an error in SABnzbd related to a watch folder that I expect is related to.

The rest of my .env file appears to be working correctly as the other variables for storage and download drives are working.

Thanks for the assistance and a great product!

**Comment by FrankExcViews** [comment]
As a follow-up it seems my containers are running with a user uid and gid of 911 for both.

**Comment by masonbivens** [comment]
I ran into a similar issue and ended up having to add `env_file: '.env'` to the compose file for the Sonarr, Radarr, and NZBGet services to set the PUID and GUID properly.

**Comment by stevewm** [comment]
Apologies for the late reply to your issue. 

Looks like masonbivens has hit on the solution though. This is something I've not encountered, likely due to using this exclusively on UnRAID.

I'll get a fix for this up later this evening after work.

**Comment by stevewm** [comment]
Pushed up a fix that should resolve the problem. Please let me know if it does!

**Comment by FrankExcViews** [comment]
I ended up manually fixing it through a method similar to what you did (Manually putting in environment variables). Either way, I am all set, thank you!
