### ISSUE TITLE
Why Watchtower over Ouroboros

### ISSUE THREAD

**Issue by chopfitzroy** [duhio/docker-compose-usenet#41]
Hey I notice that you have switched a bit between Watchtower and Ouroboros any particular reason for Watchtower over Ouroboros?

**Comment by stevewm** [comment]
I originally switched to Ouroboros due to development of Watchtower being abandoned, which is no longer the case. 

Additionally, Ouroboros at the time didn't recreate containers with the same name and would occasionally fail to clean up after itself.

**Comment by chopfitzroy** [comment]
Awesome thank you! And good to know about Ouroboros issue.
