### ISSUE TITLE
Organizr: Nginx 502 Bad Gateway

### ISSUE THREAD

**Issue by dapacruz** [duhio/docker-compose-usenet#6]
First of all, thanks for putting this together. It is great!

When trying to access Organizr, I am getting the Nginx error "502 Bad Gateway." Any ideas?

Organizr YML config:
  organizr:
    image: lsiocommunity/organizr:latest
    container_name: organizr
    hostname: organizr
    volumes:
      - ${CONFIG}/organizr:/config
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${DOMAIN}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

**Comment by stevewm** [comment]
Thanks, glad you're finding it useful.

With regards to your issue, is the Organizr container running? Could you post the logs from the container? You can get them with `docker logs organizr`.

**Comment by dapacruz** [comment]
It is indeed up as the Nginx error is coming from the container.

Name     Command   State        Ports     
organizr   /init     Up      443/tcp, 80/tcp

I should mention that this is a new deployment and I have never been able to access it. All other containers are working fine.

The following errors are repeated throughout the log file (docker-compose logs organizr):

organizr         | [27-Feb-2018 15:00:09] ERROR: [pool www] please specify user and group other than root
organizr         | [27-Feb-2018 15:00:09] ERROR: FPM initialization failed

**Comment by dapacruz** [comment]
Ah, I see the error of my ways! I created a new user and changed the global PGID and PUID. All is working now. Thanks again!

**Comment by stevewm** [comment]
Glad to hear you fixed it!
